### ISSUE TITLE
The changed feature files where to download?

### ISSUE THREAD

**Issue by alice-cool** [vipulgupta1011/swapmix#1]
Dear scholar,
 In your paper, you said modify the visual context object to another object? So the feature you changed files or data -augmentation files where to download?

**Comment by alice-cool** [comment]
(pytorch) byd@hls:~/swapmix/lxmert$ bash run/frcnn_train.bash 2 vqa_lxr955_tiny --SwapMix
Load 943000 data from split(s) train.
> /home/byd/swapmix/lxmert/src/tasks/frcnn_train.py(27)get_tuple()
-> tset = GQATorchDataset_swapmix(dset)
(Pdb)

**Comment by alice-cool** [comment]
The code stop at the below picture"(Pdb)". So what is the bug?

**Comment by vipulgupta1011** [comment]
Hi @alice-cool, thank you for your query. 

As mentioned in the paper, we modify the visual context by selecting another object from the same dataset. We do not need to download a new feature set for SwapMix perturbation. In the case of LXMERT, the mapping for the SwapMix perturbation is present at 'gqa/matching/val_dataset_mapping_new.json' and 'gqa/matching/train_dataset_mapping.json'.

We use this mapping to select the features to Swap. Make sure to download the dataset from [ReadME](https://github.com/vipulgupta1011/swapmix) and features provided by the authors of LXMERT.

Thank you for pointing out the pdb debugger checkpoint line. I have updated the file. Please pull the new [frcnn_train.py](https://github.com/vipulgupta1011/swapmix/blob/master/lxmert/src/tasks/frcnn_train.py) file.

**Comment by alice-cool** [comment]
Thanks for your timely reply. I will try the new file.&nbsp;
I think the visual bias will be a hot topic in the future.

---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年5月10日(星期二) 凌晨0:11
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [vipulgupta1011/swapmix] The changed feature files where todownload? (Issue #1)




 
Hi @alice-cool, thank you for your query.
 
As mentioned in the paper, we modify the visual context by selecting another object from the same dataset. We do not need to download a new feature set for SwapMix perturbation. In the case of LXMERT, the mapping for the SwapMix perturbation is present at 'gqa/matching/val_dataset_mapping_new.json' and 'gqa/matching/train_dataset_mapping.json'.
 
We use this mapping to select the features to Swap. Make sure to download the dataset from ReadME and features provided by the authors of LXMERT.
 
Thank you for pointing out the pdb debugger checkpoint line. I have updated the file. Please pull the new frcnn_train.py file.
