### ISSUE TITLE
Is there a result of MCAN and LXMERT on GQA test-dev and test-std set?

### ISSUE THREAD

**Issue by ChenSyEric** [vipulgupta1011/swapmix#2]
Hello, I have seen some related work on the GQA dataset. Most of them show the results on the test-dev and test-std set. Is there any result of MCAN and LXMERT on GQA test-dev and test-std set (or test-2019)?

**Comment by ChenSyEric** [comment]
Sorry, I misunderstood, this work swaps some input features of the image with other similar objects, so the answer needs to be adjusted accordingly. The answer is only known on the val dataset, and there is no answer on the test-dev and test sets.

**Comment by vipulgupta1011** [comment]
Additionally, to swap features for irrelevant objects we need object-level annotations for every image. This is not present in GQA test-dev or test set. This work is majorly a way to measure visual bias associated with any VQA model.
