### ISSUE TITLE
Evaluation takes extremely long

### ISSUE THREAD

**Issue by dreichCSL** [vipulgupta1011/swapmix#3]
I'm running evaluation with the provided MCAN model and original settings, it looks like it's evaluating per img (~10k imgs in GQA val set). Even on an RTX A6000 it takes several minutes to process just 1% of imgs. Is this normal? 
Even when setting the number of swaps to zero to evaluate the model without any swapping it takes over 1 hour to run one test. Changing batch-size and number of workers doesn't have any effect. 

Is there anything we can do to speed this up? Thanks!

**Comment by vipulgupta1011** [comment]
Hi @dreichCSL, the current code performs swapping of objects iteratively for all images in the test set. The speed of evaluation is indeed slow. A thing that can be done for speedup is loading and evaluating multiple models simultaneously. Swapping features using SwapMix is the most time-consuming part, multithreading in that part will definitely speed this up.
